apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    environment: dev
    team: backend

---

apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    team: backend

---

apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: prod
    team: backend

