apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
  namespace: development
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          while true; do
            echo "$(date) - App is processing request #$RANDOM" >> /var/log/app.log
            sleep 5
          done
      volumeMounts:
        - mountPath: /var/log
          name: shared-logs

    - name: log-shipper
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          echo "Log shipper started. Tailing app logs..."
          tail -f /var/log/app.log  | while read line; do
            echo "[SHIPPED] $line"
          done
      volumeMounts:
        - mountPath: /var/log
          name: shared-logs

  volumes:
    - name: shared-logs
      emptyDir: {}
