apiVersion: v1
kind: Service
metadata:
  name: myapp-headless
  namespace: development
spec:
  clusterIP: None
  selector:
    app: mydb
  ports:
  - port: 3000
    targetPort: 3000

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mydb
  namespace: development
spec:
  selector:
    matchLabels:
      app: mydb
  serviceName: myapp-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: myapp:1.0
        ports:
        - containerPort: 3000
        env:
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ENVIRONMENT
            value: "database-mode"
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 500Mi
